// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================
// ==============================================
// Please do not change the implementations below
// ==============================================
#include "AbstractDustyGasSolver.h"

#include "kernels/aderdg/generic/Kernels.h"

#include "kernels/GaussLegendreBasis.h"
#include "kernels/GaussLobattoBasis.h"

#include "DustyGasSolver_Variables.h"
#include "DustyGasSolver.h" // Have to include a proper declaration. Cannot use forward declared classes in static_cast.

#include <stdio.h>

// quadrature weights and operators
double**   DustyGas::AbstractDustyGasSolver::weights                                 = kernels::legendre::weights;
double**   DustyGas::AbstractDustyGasSolver::nodes                                   = kernels::legendre::nodes;
double***  DustyGas::AbstractDustyGasSolver::Kxi                                     = kernels::legendre::Kxi;
double***  DustyGas::AbstractDustyGasSolver::dudx                                    = kernels::legendre::dudx;
double***  DustyGas::AbstractDustyGasSolver::iK1                                     = kernels::legendre::iK1;
double***  DustyGas::AbstractDustyGasSolver::equidistantGridProjector                = kernels::legendre::equidistantGridProjector;
double***  DustyGas::AbstractDustyGasSolver::FCoeff                                  = kernels::legendre::FCoeff;
double**** DustyGas::AbstractDustyGasSolver::fineGridProjector                       = kernels::legendre::fineGridProjector;
kernels::UnivariateFunction** DustyGas::AbstractDustyGasSolver::basisFunction                 = kernels::legendre::basisFunction;
kernels::UnivariateFunction** DustyGas::AbstractDustyGasSolver::basisFunctionFirstDerivative  = kernels::legendre::basisFunctionFirstDerivative;
kernels::UnivariateFunction** DustyGas::AbstractDustyGasSolver::basisFunctionSecondDerivative = kernels::legendre::basisFunctionSecondDerivative;

// We define the constructor of the actual solver here in order to regenerate it easily.
DustyGas::DustyGasSolver::DustyGasSolver(
  const double maximumMeshSize,
  const int maximumMeshDepth,
  const int haloCells,
  const int haloBufferCells,
  const int limiterBufferCells,
  const int regularisedFineGridLevels,
  const exahype::solvers::Solver::TimeStepping timeStepping,
  const int DMPObservables
)
  :
  AbstractDustyGasSolver::AbstractDustyGasSolver(
      maximumMeshSize,
      maximumMeshDepth,
      haloCells,
      haloBufferCells,
      limiterBufferCells,      
      regularisedFineGridLevels,
      timeStepping,
      DMPObservables
) {
}


DustyGas::AbstractDustyGasSolver::AbstractDustyGasSolver(
    const double maximumMeshSize,
    const int maximumMeshDepth,
    const int haloCells,
    const int haloBufferCells,
    const int limiterBufferCells,
    const int regularisedFineGridLevels,
    const exahype::solvers::Solver::TimeStepping timeStepping,
    const int DMPObservables
)
  :
  exahype::solvers::ADERDGSolver(
      "DustyGasSolver",
      NumberOfVariables,
      NumberOfParameters,
      NumberOfGlobalObservables,
      Order+1,
      maximumMeshSize,
      maximumMeshDepth,
      haloCells,
      haloBufferCells,
      limiterBufferCells,
      regularisedFineGridLevels,
      timeStepping,
      DMPObservables
) {
}

void DustyGas::AbstractDustyGasSolver::constantsToString(std::ostream& os) {
  // This string is used in the --version output to identify compile time constants
  os << "DustyGas::AbstractDustyGasSolver("
     << "nVar=" << NumberOfVariables << ", "
     << "nParam=" << NumberOfParameters << ", "
     << "Order=" << Order
     << ")";
}

void DustyGas::AbstractDustyGasSolver::abortWithMsg(const char* const msg) {
  // verbosily fail even without assertions turned on
  puts(msg);
  abort();
}

int DustyGas::AbstractDustyGasSolver::fusedSpaceTimePredictorVolumeIntegral(double* lduh, double* lQhbnd, double* lGradQhbnd, double* lFhbnd, double* const luh, const tarch::la::Vector<DIMENSIONS, double>& cellCentre, const tarch::la::Vector<DIMENSIONS, double>& cellSize, const double t ,const double dt,const bool addVolumeIntegralResultToUpdate) {
  constexpr int spaceBasisSize     = (Order+1)*(Order+1);
  constexpr int spaceTimeBasisSize = spaceBasisSize*(Order+1);
  constexpr int sizeLQi   = (NumberOfVariables+NumberOfParameters)*spaceTimeBasisSize;
  constexpr int sizeRhs   = sizeLQi;
  constexpr int sizeLFi   = (DIMENSIONS + 1)*NumberOfVariables*spaceTimeBasisSize;
  constexpr int sizeGradQ = DIMENSIONS*NumberOfVariables*spaceBasisSize;
  
  constexpr int sizeLQhi = (NumberOfVariables+NumberOfParameters)*spaceBasisSize;
  constexpr int sizeLFhi = (DIMENSIONS + 1)*NumberOfVariables*spaceBasisSize;

  
  constexpr int totalSize = sizeLQi + sizeRhs + sizeLFi + sizeGradQ +
                            sizeLQhi + sizeLFhi;

  double block[totalSize];
  double* memory = block;
      
  double* lQi   = memory; memory+=sizeLQi;
  double* rhs   = memory; memory+=sizeRhs;
  double* lFi   = memory; memory+=sizeLFi;
  double* gradQ = memory; memory+=sizeGradQ;
  
  double* lQhi = memory; memory+=sizeLQhi;
  double* lFhi = memory; memory+=sizeLFhi;
  const int picardIterations = kernels::aderdg::generic::c::spaceTimePredictorNonlinear<false, true, false, false, false, DustyGasSolver>(*static_cast<DustyGasSolver*>(this), lQhbnd, lGradQhbnd, lFhbnd, lQi, rhs, lFi, gradQ, lQhi, lFhi, luh, cellCentre, tarch::la::invertEntries(cellSize), t, dt);
 
  if ( addVolumeIntegralResultToUpdate ) {
    kernels::aderdg::generic::c::volumeIntegralNonlinear<DustyGasSolver, false, true, false, NumberOfVariables, Order+1>(lduh,lFhi,cellSize); 
  } else { // directly add the result to the solution
    double tempUpdate[NumberOfVariables*spaceBasisSize] = {0.0};
    kernels::aderdg::generic::c::volumeIntegralNonlinear<DustyGasSolver, false, true, false, NumberOfVariables, Order+1>(tempUpdate,lFhi,cellSize);
    addUpdateToSolution(luh,luh,tempUpdate,dt);
  }
  

  return picardIterations;
}

void DustyGas::AbstractDustyGasSolver::addUpdateToSolution(double* const luh,const double* const luhOld,const double* const lduh,const double dt) {
  kernels::aderdg::generic::c::solutionUpdate<DustyGasSolver>(*static_cast<DustyGasSolver*>(this),luh,luhOld,lduh,dt);
}

void DustyGas::AbstractDustyGasSolver::faceIntegral(double* const out/*may be solution or update vector*/,double* const lFhbnd,const int direction, const int orientation,const tarch::la::Vector<DIMENSIONS-1,int>& subfaceIndex,const int levelDelta,const tarch::la::Vector<DIMENSIONS, double>& cellSize,const double dt,const bool addToUpdate) {
    
  constexpr int basisSize2 = (Order+1);
  constexpr int basisSize3 = basisSize2*(Order+1);
  constexpr int sizeUpdate = NumberOfVariables*basisSize3;

  
  if ( levelDelta > 0 ) {
    constexpr int sizeFlux = NumberOfVariables*basisSize2;
    double lFhbndCoarse[sizeFlux];
    kernels::aderdg::generic::c::faceUnknownsRestriction<DustyGasSolver,NumberOfVariables,Order+1>(lFhbndCoarse,lFhbnd,subfaceIndex,levelDelta);
    tarch::la::Vector<DIMENSIONS,double> coarseGridCellSize = tarch::la::aPowI(levelDelta,3) * 1.0 * cellSize;
    
    kernels::aderdg::generic::c::faceIntegralNonlinear<DustyGasSolver,NumberOfVariables,Order+1>(out,lFhbndCoarse,direction,orientation,coarseGridCellSize);
  } else {
    if ( addToUpdate ) {
      kernels::aderdg::generic::c::faceIntegralNonlinear<DustyGasSolver,NumberOfVariables,Order+1>(out,lFhbnd,direction,orientation,cellSize);
    } else { // solution is only available in real cells, i.e. only here we can directly add the face integral result to the solution
      double lduh[sizeUpdate] = {0.0};                   // initialise with zeros
      kernels::aderdg::generic::c::faceIntegralNonlinear<DustyGasSolver,NumberOfVariables,Order+1>(lduh,lFhbnd,direction,orientation,cellSize);
      addUpdateToSolution(out,out,lduh,dt);
    }
  }
  
}

void DustyGas::AbstractDustyGasSolver::riemannSolver(double* const FL,double* const FR,const double* const QL,const double* const QR,const double t,const double dt, const tarch::la::Vector<DIMENSIONS, double>& cellSize, const int direction, bool isBoundaryFace, int faceIndex) {
  assertion2(direction>=0,dt,direction);
  assertion2(direction<DIMENSIONS,dt,direction);
kernels::aderdg::generic::c::riemannSolverNonlinear<false,false,DustyGasSolver>(*static_cast<DustyGasSolver*>(this),FL,FR,QL,QR,t,dt,cellSize,direction);
}

void DustyGas::AbstractDustyGasSolver::boundaryConditions(double* const fluxIn,const double* const stateIn,const double* const gradStateIn, const double* const luh,const tarch::la::Vector<DIMENSIONS,double>& cellCentre,const tarch::la::Vector<DIMENSIONS,double>& cellSize,const double t,const double dt,const int direction,const int orientation) {
  constexpr int basisSize     = (Order+1);
  constexpr int sizeStateOut = (NumberOfVariables+NumberOfParameters)*basisSize;
  constexpr int sizeFluxOut  = NumberOfVariables*basisSize;
  
  constexpr int totalSize = sizeStateOut + sizeFluxOut;
  double block[totalSize];
  double* memory = block;

  double* stateOut = memory; memory+=sizeStateOut;
  double* fluxOut  = memory; memory+=sizeFluxOut;

  const int faceIndex = 2*direction+orientation;
    kernels::aderdg::generic::c::boundaryConditions<false,DustyGasSolver>(*static_cast<DustyGasSolver*>(this),fluxOut,stateOut,fluxIn,stateIn,gradStateIn,cellCentre,cellSize,t,dt,faceIndex,direction);
  if ( orientation==0 ) {
    double* FL = fluxOut; const double* const QL = stateOut;
    double* FR = fluxIn;  const double* const QR = stateIn;
  
    riemannSolver(FL,FR,QL,QR,t,dt,cellSize,direction,true,faceIndex);
  }
  else {
    double* FL = fluxIn;  const double* const QL = stateIn;
    double* FR = fluxOut; const double* const QR = stateOut;

    riemannSolver(FL,FR,QL,QR,t,dt,cellSize,direction,true,faceIndex);
  }
}

double DustyGas::AbstractDustyGasSolver::stableTimeStepSize(const double* const luh,const tarch::la::Vector<DIMENSIONS,double>& cellSize) {
  double d = kernels::aderdg::generic::c::stableTimeStepSize<DustyGasSolver,false>(*static_cast<DustyGasSolver*>(this),luh,cellSize);
  return d;
}
void DustyGas::AbstractDustyGasSolver::adjustSolution(double* const luh,const tarch::la::Vector<DIMENSIONS,double>& cellCentre,const tarch::la::Vector<DIMENSIONS,double>& cellSize,double t,double dt) {
  kernels::aderdg::generic::c::solutionAdjustment<DustyGasSolver>(*static_cast<DustyGasSolver*>(this),luh,cellCentre,cellSize,t,dt);
}

void DustyGas::AbstractDustyGasSolver::faceUnknownsProlongation(double* const lQhbndFine,double* const lFhbndFine,const double* const lQhbndCoarse,const double* const lFhbndCoarse,const int coarseGridLevel,const int fineGridLevel,const tarch::la::Vector<DIMENSIONS-1,int>& subfaceIndex) {
  kernels::aderdg::generic::c::faceUnknownsProlongation<DustyGasSolver,NumberOfVariables,NumberOfParameters,Order+1>(lQhbndFine,lFhbndFine,lQhbndCoarse,lFhbndCoarse,coarseGridLevel,fineGridLevel,subfaceIndex);
}

void DustyGas::AbstractDustyGasSolver::volumeUnknownsProlongation(double* const luhFine,const double* const luhCoarse,const int coarseGridLevel,const int fineGridLevel,const tarch::la::Vector<DIMENSIONS,int>& subcellIndex) {
  kernels::aderdg::generic::c::volumeUnknownsProlongation<DustyGasSolver,NumberOfVariables,NumberOfParameters,Order+1>(luhFine,luhCoarse,coarseGridLevel,fineGridLevel,subcellIndex);
}

void DustyGas::AbstractDustyGasSolver::volumeUnknownsRestriction(double* const luhCoarse,const double* const luhFine,const int coarseGridLevel,const int fineGridLevel,const tarch::la::Vector<DIMENSIONS,int>& subcellIndex) {
  kernels::aderdg::generic::c::volumeUnknownsRestriction<DustyGasSolver,NumberOfVariables,NumberOfParameters,Order+1>(luhCoarse,luhFine,coarseGridLevel,fineGridLevel,subcellIndex);
}

//--------


void DustyGas::AbstractDustyGasSolver::resetGlobalObservables(double* const globalObservables) {
}

void DustyGas::AbstractDustyGasSolver::updateGlobalObservables(
    double* const                               globalObservables,
    const double* const                         luh,
    const tarch::la::Vector<DIMENSIONS,double>& cellCentre,
    const tarch::la::Vector<DIMENSIONS,double>& cellSize,
    const double t,
    const double dt) {
}

void DustyGas::AbstractDustyGasSolver::mergeGlobalObservables(double* const globalObservables,const double* const otherObservables) {
}

void DustyGas::AbstractDustyGasSolver::wrapUpGlobalObservables(double* const globalObservables) {
}

//--------

void DustyGas::AbstractDustyGasSolver::flux(const double* const Q,double** const F) {
      abortWithMsg("flux: If this operation is entered, you have activated the corresponding guard. Then you have to re-implement this routine, too." );
}

void DustyGas::AbstractDustyGasSolver::viscousFlux(const double* const Q,const double* const gradQ, double** const F) {
      abortWithMsg("viscous flux: If this operation is entered, you have activated the corresponding guard. Then you have to re-implement this routine, too." );
}

void DustyGas::AbstractDustyGasSolver::viscousEigenvalues(const double* const Q,const int direction,double* const lambda) {
      abortWithMsg("viscous eigenvalues: If this operation is entered, you have activated the corresponding guard. Then you have to re-implement this routine, too." );
}

void DustyGas::AbstractDustyGasSolver::algebraicSource(const tarch::la::Vector<DIMENSIONS, double>& x, double t, const double *const Q, double *S) {
      abortWithMsg("algebraicSource: If this operation is entered, you have activated the corresponding guard. Then you have to re-implement this routine, too." );
}

    void DustyGas::AbstractDustyGasSolver::nonConservativeProduct(const double* const Q,const double* const gradQ,double* const BgradQ) {
      abortWithMsg("nonConservativeProduct: If this operation is entered, you have activated the corresponding guard. Then you have to re-implement this routine, too." );
}

void DustyGas::AbstractDustyGasSolver::multiplyMaterialParameterMatrix(const double* const Q, double** const rhs) {
      abortWithMsg("multiplyMaterialParameterMatrix: If this operation is entered, you have activated the corresponding guard. Then you have to re-implement this routine, too." );
}

void DustyGas::AbstractDustyGasSolver::pointSource(const double* const Q,const double* const x,const double t,const double dt, double* const forceVector,int n) {
      abortWithMsg("pointSource: If this operation is entered, you have activated the corresponding guard. Then you have to re-implement this routine, too." );
}

void DustyGas::AbstractDustyGasSolver::resetGlobalObservables(GlobalObservables& globalObservables) const {
  abortWithMsg("If this operation is entered (resetGlobalObservables), you have specified global observables. Then you have to re-implement this routine, too." );
}

void DustyGas::AbstractDustyGasSolver::mapGlobalObservables(
    GlobalObservables&                          globalObservables,
    const double* const                         luh,
    const tarch::la::Vector<DIMENSIONS,double>& cellCentre,
    const tarch::la::Vector<DIMENSIONS,double>& cellSize,
    const double t,
    const double dt) const {
  abortWithMsg("If this operation is entered (mapGlobalObservables), you have specified global observables. Then you have to re-implement this routine, too." );
}

void DustyGas::AbstractDustyGasSolver::mergeGlobalObservables(
    GlobalObservables&         globalObservables,
    ReadOnlyGlobalObservables& otherObservables) const {
  abortWithMsg("If this operation is entered (mergeGlobalObservables), you have specified global observables. Then you have to re-implement this routine, too." );
}

void DustyGas::AbstractDustyGasSolver::wrapUpGlobalObservables(GlobalObservables& globalObservables) const {
  // Please re-implement if required.
}


/**
 * Fallback implementations of joined functions. Users can either safely ignore this
 * or overwrite with their own implementations.
 **/
#include "kernels/fusedMethods.cpph"