// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "DustyGasWriter.h"

DustyGas::DustyGasWriter::DustyGasWriter(DustyGas::DustyGasSolver& solver) {
  // @TODO Please insert your code here.
}

DustyGas::DustyGasWriter::~DustyGasWriter() {
}

void DustyGas::DustyGasWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void DustyGas::DustyGasWriter::finishPlotting() {
  // @TODO Please insert your code here.
}

void DustyGas::DustyGasWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 4;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = Q[i];
  }
}